blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path
    ('category/<category>/', views.CategoryListView.as_view(),
        name='category'),
    path('new_ink/', views.AddInkPost.as_view(), name='create_ink'),
    path('like/<slug:slug>', views.InkLike.as_view(), name='inkpost_like'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='ink_detail'),
    path('update/<slug:slug>', views.UpdateInkView.as_view(),
         name='update_ink'),
    path('delete/<slug:slug>', views.DeleteInkView.as_view(),
         name='delete_ink'),
]

inspired_ink/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog_urls'),
    path('accounts/', include('allauth.urls')),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.template.defaultfilters import slugify

STATUS = ((0, "Draft"), (1, "Post"))


class Category(models.Model):
    name = models.CharField(max_length=80)

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    Adds the structure of the Ink (post).
    Source from Code Institute:
    https://github.com/Code-Institute-Solutions/Django3blog/blob/master/11_messages/blog/models.py#:~:text=class%20Post(,.count()
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts")
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    excerpt = models.TextField(max_length=100, blank=True)
    content = models.TextField()
    status = models.IntegerField(choices=STATUS, default=True)
    likes = models.ManyToManyField(
        User, related_name='blog_likes', blank=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs):
        """
        method to generate slug for posts
        by non-admin users
        """
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)


class Comment(models.Model):
    """
    Adds the structure of an Ink (post) comment.
    Source from Code Institute:
    https://github.com/Code-Institute-Solutions/Django3blog/blob/master/11_messages/blog/models.py#:~:text=class%20Comment(,name%7D%22
    """
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

templates/add_ink.html
{% extends "base.html" %}
{% block title %}Create a new Ink{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<!--
    Template for authenticated users 
    to create a new Ink post    
-->

<div class="container add-ink">
    <div class="row add-ink-text">
        <h2>Write an Ink</h2>
        <p>Here is where you write your new ink!</p>
        <p>Be it a poem, a haiku, or a short story, it fits right here.</p>
    </div>

    <form class="form-group" method="POST">
        {% csrf_token %}
        {{ form.as_p | safe }}
        <button class="btn btn-primary" type="submit">Submit</button>
        <a href="{% url 'home' %}" role="button" class="btn">Cancel</a>
    </form>
</div>
{% endblock content %}

templates/add_post.html
{% extends "base.html" %}
{% block title %}Create a new Ink{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<h2>Add Ink</h2>

<div class="container-fluid intro-text">
    <div class="row">
        Here is where you write your new ink!
    </div>
</div>

<form method="POST">   
    {% csrf_token %}
    {{ form.as_p | safe }}
    <button type="submit" class="submit-btn">Submit</button>
</form>
<a href="{% url 'home' %}" role="button" class="cancel-btn">Cancel</a>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- BOOTSTRAP -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
    </script>

    <!-- ICONIFY-->
    <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>

    <!-- GOOGLE FONTS-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Inknut+Antiqua:wght@300&family=Montserrat&family=Roboto:wght@300&display=swap"
        rel="stylesheet">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>

    <!-- NAVBAR -->

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Inspired Ink <iconify-icon icon="mdi:ink">
            </iconify-icon>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for category in category_list %}
                        <a class="dropdown-item" href="/category/{{category.name}}">
                            {{category.name|title}}
                        </a>
                        {% endfor %}
                    </div>
                </li>
                {% if user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'create_ink' %}">Create new Ink</a></li>
                <li><a class="nav-link" href="{% url 'account_logout' %}">Sign out</a></li>
                {% else %}
                <li><a class="nav-link" href="{% url 'account_login' %}">Sign in</a></li>
                <li><a class="nav-link" href="{% url 'account_signup' %}">Create Account</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="background-img">

        <!-- ALERT MESSAGES -->

        <div class="col-md-8 offset-md-2">
            {% for message in messages %}
            <div class="alert {{ message.tags}} alert-dismissible fade show" id="alert-msg" role="alert">
                {{ message | safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>

        {% block content %}

        {% endblock content %}
    </div>

    <!-- FOOTER -->

    <footer class="footer container-fluid d-flex justify-content-center">
        <a href="https://twitter.com/" target="_blank" rel="noopener noreferrer" aria-label="Twitter">
            <iconify-icon icon="mdi:twitter"></iconify-icon>
        </a>
        <a href="https://www.facebook.com/" target="_blank" rel="noopener noreferrer" aria-label="Facebook">
            <iconify-icon icon="mdi:facebook"></iconify-icon>
        </a>
        <a href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer" aria-label="Instagram">
            <iconify-icon icon="mdi:instagram"></iconify-icon>
        </a>
        <a href="https://www.pinterest.com/" target="_blank" rel="noopener noreferrer" aria-label="Instagram">
            <iconify-icon icon="mdi:pinterest"></iconify-icon>
        </a>
    </footer>

    <!-- ALERT MESSAGE TIMEOUT -->
    <!-- Source for alert messages: 
        https://github.com/Code-Institute-Solutions/Django3blog/blob/master/11_messages/templates/base.html#:~:text=%3Cscript%3E,%3C/script%3E
        -->
    <script>
        setTimeout(function () {
            let msg = document.getElementById("alert-msg");
            let alert = new bootstrap.Alert(msg);
            alert.close();
        }, 3000);
    </script>

</body>

</html>

templates/category.html
{% extends "base.html" %}

{% block title %}
{{categorylist.cat}} inks
{% endblock %}

{% block content %}

<!--
  Template for the layout of the
  category section
-->

<h1 class="category-text">List of {{categorylist.cat}} inks</h1>

<div class="container-fluid">
  <div class="row d-flex justify-content-around p-3 m-1">
    {% for post in categorylist.posts %}
      <div class="card ink-cards m-3">
          <div class="card-body">
              <a href="{% url 'ink_detail' post.slug %}" class="card-link">
                  <p class="card-title">
                      <iconify-icon icon="mdi:ink"></iconify-icon> {{ post.title }}
                  </p>
                  <p class="card-title mb-2">A {{post.category}} by {{post.author}}</p>
                  <p class="card-subtitle mb-2">Written: {{post.created_on}}</p>
                  <p class="card-text">{{ post.excerpt }}</p>
                  <p>
                      <iconify-icon icon="mdi:ink"></iconify-icon> {{ post.number_of_likes }}
                  </p>
              </a>
          </div>
      </div>
      {% endfor %}
  </div>
  <!--
    Source for button centering:
    https://stackoverflow.com/questions/41664991
    Source for previous page button:
    https://stackoverflow.com/questions/2968425/
  -->
  <div class="col text-center"><button class="btn" type="button" onclick="history.back();">Back</button></div>
  <br>
</div>

<!-- PAGINATION -->
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Inspired Ink{% endblock %}

{% block content %}

<!-- QUOTE -->

<div class="container">
    <div class="row justify-content-center quote-card">
        <div class="card col-8 card-wrapper">
            <div class="card-header">
                Quote
            </div>
            <div class="card-body quote-body">
                <blockquote class="blockquote mb-0">
                    <p>“Write what disturbs you, what you fear, what you have not been willing to speak about. Be
                        willing to be split open.”</p>
                        <br>
                    <footer class="blockquote-footer">Natalie Goldberg <cite title="Source Title">Writing Down the
                            Bones: Freeing the Writer Within</cite>
                    </footer>
                </blockquote>
            </div>
        </div>
    </div>
</div>

<!-- INTRODUCTION -->

<div class="wrapper intro-text container-fluid">
    <hr>
    <div class="row">
        <h1>- Welcome to Inspired Ink -</h1>
        <br>
        <p>
            Inspired Ink is a place for creative writing where you, as an author
            can post a variety of different pieces, sharing them with a like-minded
            people to enjoy.
        </p>
        <p> 
            <br>
            Here, you can get inspired and grow your creative mind by giving and
            receiving feedback on your work, or simply enjoying a myriad of creative
            works from people far and wide.
        </p>
         <p>
            <br>
            Show your appreciation by adding an ink drop 
            <iconify-icon icon="mdi:ink-plus-outline"></iconify-icon> to those who 
            made you feel something extra and involve yourself in the topic!
            Did the Ink make you ponder life or laugh? Let them know!
        </p>
        <p>
            <br>
            Everyone from every step on their journey, from beginners to veterans,
            are welcome to share their writing by adding more Ink to the (web)page.
        </p>
        <p>
            <br>
            If this sounds like a place you'd like to call home, then
            <br>
            <small><iconify-icon icon="mdi:ink"></iconify-icon></small>
                <a href="{% url 'account_signup' %}">Create an account</a>
                <small><iconify-icon icon="mdi:ink"></iconify-icon></small>
            <br>
            to start memorializing your creative journey!
        </p>
    </div>
    <hr>
</div>

<!-- POSTED INKS-->

<h2>Read an Ink and get inspired!</h2>

<div class="container-fluid">
    <div class="row d-flex justify-content-around p-3 m-1">
        {% for post in post_list %}
        <div class="card ink-cards m-3">
            <div class="card-body">
                <a href="{% url 'ink_detail' post.slug %}" class="card-link">
                    <p class="card-title">
                        <iconify-icon icon="mdi:ink"></iconify-icon> {{ post.title }}
                    </p>
                    <p class="card-title">A {{post.category}} by {{post.author}}</p>
                    <p class="card-text">{{ post.excerpt }}</p>
                    <p>
                        <iconify-icon icon="mdi:ink"></iconify-icon> {{ post.number_of_likes }}
                    </p>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<!-- PAGINATION -->
{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

        {% endif %}
    </ul>
</nav>
{% endif %}

{% endblock %}

templates/ink_delete.html
{% extends "base.html" %}

{% block title %}Delete Ink{% endblock %}

{% block content %}

<!--
    Template for the layout of
    when a user wants to delete
    one of their Inks
-->

<br>
<h2 class="m-4">Are you sure you want to delete your Ink? <br>
    The decision is final.</h2> <br>

<!-- Delete posted Ink for the author who
wrote it, ensuring no one else can delete other's
Inks -->
{% if user.id == post.author.id %}
<form method="POST">
    {% csrf_token %}
    <div class="button-wrap">
        <div class="update-btn-group">
            <button type="submit" class="btn delete-btn">Yes, my decision is final.</button>
            <a href="{% url 'home' %}" role="button" class="btn">No, I have regrets!</a>
        </div>
    </div>
</form>
{% endif %}

{% endblock %}

templates/ink_detail.html
{% extends 'base.html' %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}

{% load crispy_forms_tags %}

<!--
    Template for the layout of when
    a user views a full Ink post
-->

<!-- VIEW INK POST -->

<div class="card-wrapper offset-md-2">
    <div class="card border-secondary mb-3">
        <div class="card-header">
            <h1>{{ post.title }}</h1>
        </div>
        <div class="card-body text-secondary">
            <h5 class="card-title">{{ post.author }} | {{ post.created_on}}</h5>
            <!--Source add linebreaks:
            https://code-institute-room.slack.com/archives/C8N285L9H/p1521104005000292-->
            <p class="card-text ink-content">{{ post.content | linebreaksbr | safe }}</p>
        </div>
    </div>

    {% if user.id == post.author.id %}
    <div class="update-btn-group">
        <a href="{% url 'update_ink' post.slug %}" class="btn" role="button">Edit</a>
        <a href="{% url 'delete_ink' post.slug %}" class="btn" role="button">Delete</a>
    </div>
    {% endif %}

    <!-- LIKES AND COMNMENTS SYMBOLS -->

    <br>
    {% if user.is_authenticated %}
    <form class="d-inline" action="{% url 'inkpost_like' post.slug %}" method="POST">
        {% csrf_token %}
        {% if liked %}
        <button type="submit" name="inkpost_id" value="{{ post.slug }}" class="btn-like"
            aria-label="like or unlike post">
            <iconify-icon icon="mdi:ink-plus"></iconify-icon>
        </button>
        {% else %}
        <button type="submit" name="inkpost_id" value="{{ post.slug }}" class="btn-like"
            aria-label="like or unlike post">
            <iconify-icon icon="mdi:ink-plus-outline"></iconify-icon>
        </button>
        {% endif %}
    </form>
    {% else %}
    <iconify-icon icon="mdi:ink" class="icon"></iconify-icon>
    {% endif %}
    <span class="number-of-likes">{{ post.number_of_likes }}</span>

    {% with comments.count as total_comments %}
    <iconify-icon icon="material-symbols:comment" class="icon"></iconify-icon> {{ total_comments }}
    {% endwith %}
</div>

<!-- SHOW COMMENTS -->

<div class="container-fluid">
    <div class="row comment-wrap">
        <div class="card col m-4">
            <div class="card-title">
                <h3>Feedback:</h3>
            </div>
            <div class="card-body">
                {% for comment in comments %}
                <p class="font-weight-bold">
                    {{ comment.name }}
                    <span class=" text-muted font-weight-normal">
                        {{ comment.created_on }}
                    </span> wrote:
                </p>
                {{ comment.body | linebreaks }}
                <hr>
                <!---Source for adding text to container if it's empty:
                https://stackoverflow.com/questions/17435233-->
                {% empty %}
                {% if user.is_authenticated %}
                <p>No one has left any feedback yet!<br>
                    Maybe you want to be the first?</p>

                {% else %}

                <p>No one has left any feedback yet!<br>
                    Maybe you want to be the first? <br><br>
                    If so, <a href="{% url 'account_login' %}">sign in</a> or <a
                        href="{% url 'account_signup' %}">create an account!</a></p>

                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- LEAVE COMMENT FOR AUTHENTICATED USERS -->
    <div>
        <div class="row comment-wrap">
            {% if user.is_authenticated %}
            <div class="card col m-4">
                <div class="card-title">
                    <h3>Leave feedback:</h3>
                </div>
                <div class="card-body">
                    <p>Comment as: {{ user.username }}</p>
                    <form method="post">
                        {{ feedback_form | crispy }}
                        {% csrf_token %}
                        <br>
                        <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
            <!--
        Source for button centering:
        https://stackoverflow.com/questions/41664991
        Source for previous page button:
        https://stackoverflow.com/questions/2968425/
        -->
        <div class="col text-center"><button class="btn" type="button" onclick="history.back();">Back</button></div>
        <br>
    </div>
</div>


{% endblock content %}

templates/ink_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit Ink{% endblock %}

{% block content %}

<!--
    Template for the layout of
    when an authenticated user
    wants to edit their Ink
-->

<br>
<h2>Edit your Ink</h2>

<!-- Edit posted Ink for the author who
wrote it, ensuring no one else can edit other's
Inks -->

<div class="container add-ink">
    <div class="row add-ink-text">
        <h2>Add Ink</h2>
        <p>Here is where you write your new ink!</p>
        <p>Be it a poem, a haiku, or a short story, it fits right here.</p>
    </div>
</div>

<div class="container add-ink">
    {% if user.id == post.author.id %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p | safe }}
        <button type="submit" class="btn">Update</button>
        <a href="{% url 'home' %}" role="button" class="btn">Cancel</a>
    </form>
</div>

{% endif %}

{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <div class="row">
        <h1>{{ post.title }}</h1>
    </div>
    <div class="row">
        <p>{{ post.author }} | {{ post.created_on}}</p>
    </div>
</div>

<div class="card">
    <div class="row">
        <div class="card-body">
            <p class="card-text">
                {{ post.content | safe }}
            </p>
        </div>

        <div class="col-1">
            {% if user.is_authenticated %}
            <form class="d-inline" action="{% url 'inkpost_like' post.slug %}" method="POST">
                {% csrf_token %}
                {% if liked %}
                <button type="submit" name="inkpost_id" value="{{ post.slug }}" class="btn-like">
                    <strong><iconify-icon icon="teenyicons:heart-solid"></iconify-icon></strong>
                </button>
                {% else %}
                <button type="submit" name="inkpost_id" value="{{ post.slug }}" class="btn-like">
                    <strong><iconify-icon icon="teenyicons:heart-outline"></iconify-icon></strong>
                </button>
                {% endif %}
            </form>
            {% else %}
                <strong><iconify-icon icon="teenyicons:heart-solid"></iconify-icon>
            {% endif %}
            <span>{{ post.number_of_likes }} </span></strong>
        </div>
        <div class="col-1">
            {% with comments.count as total_comments %}
            <strong><iconify-icon icon="material-symbols:comment"></iconify-icon> {{ total_comments }}</strong>
            {% endwith %}
        </div>
    </div>

    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 card mb-4 mt3">
            <h3>Comments:</h3>
            <div class="card-cody">
                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            {{ comment.created_on }}
                        </span> wrote:
                    </p>
                    {{ comment.body | linebreaks }}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card">
            {% if user.is_authenticated %}
            <h3>Leave a comment:</h3>
            <p>Posting as: {{ user.username }}</p>
            <form method="post" style="margin-top: 1.3em;">
                {{ feedback_form | crispy }}
                {% csrf_token %}
                <button type="submit" class="btn btn-signup btn-lg">Submit</button>
            </form>
            {% endif %}
        </div>
    </div>
</div>

{% if user.id == post.author.id %}
    <div class="update-btn-group">
        <a href="{% url 'update' post.slug %}" class="edit-btn" role="button">Edit</a>
    </div>
{% endif %}

<a role="button" href="{% url 'home' %}">Return</a>

{% endblock content %}

templates/update_post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit Ink{% endblock %}

{% block content %}

<h2>Edit your Ink</h2>   

<!-- Edit posted Ink for the author who
wrote it, ensuring no one else can edit others
Inks -->
{% if user.id == post.author.id %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p | safe }}
        <div class="update-btn-group">
            <button type="submit" class="edit-btn">Update</button>
            <a href="{% url 'home' %}" role="button" class="cancel-btn">Cancel</a>
        </div>
    </form>
{% endif %}

{% endblock %}